location choise update
Studio-Yandex-Practicum/mspp pull request #23
Opened 2023-02-19 10:25 UTC by ADYason

2023-02-19 10:36 UTC, ADYason commented
Изменен способо получения данных при выборе региона. После заполнения поля “Возраст” Идет обращение к табличке bot_coveragearea.

2023-02-25 22:18 UTC, kr0t requested changes

2023-02-25 22:18 UTC, kr0t commented on src/apps/bot/handlers.py
> +    async for region in CoverageArea.objects._mptt_filter(level=0):
А тут точно нужен `async`? Выглядит как будто ты просто итерируешься по структуре.
`_mptt_filter()` можешь показать документацию на этот метод? Да и в целом лучше стоит сделать скрин каст, как это выглядит в боте. Я пока не смог воспроизвести локально.

2023-02-25 22:18 UTC, kr0t commented on src/apps/bot/handlers.py
> +    from .models import CoverageArea
Давай вынесем импорт на уровень файла, он ещё понадобится в других местах.

2023-02-25 22:18 UTC, kr0t commented on src/apps/bot/handlers.py
>      print("start user_data:", context.user_data)  # FIXME: удалить
Это надо отсюда убрать.

2023-02-25 22:18 UTC, kr0t commented on src/apps/bot/handlers.py
> +    async for region in CoverageArea.objects._mptt_filter(level=1):
Зачем тут `async`? Кажется что его можно тут не использовать.

2023-02-25 22:18 UTC, kr0t commented on src/apps/bot/handlers.py
> +        regions_buttons.insert(0, [InlineKeyboardButton(region.name, callback_data=region.name)])
Мне кажется что более правильно тут сгенерировать список кнопок например с помощью list comprehension а затем сделать append 2-х кнопок которые есть всегда.
Инсерт в список более [дорогостоящая](https://wiki.python.org/moin/TimeComplexity) операция чем append.

2023-02-26 09:57 UTC, ADYason commented on src/apps/bot/handlers.py
> +    async for region in CoverageArea.objects._mptt_filter(level=0):
Без `async` неполучится, тк при последовательном обращении к бд бот ломается. Я писал об этом в [треде](https://app.pachca.com/chats?thread_id=305101) в самом начале. Первое сообщение.
Документации этого метода нет, тк он служебный для библиотеки. 
Переписал для метода `filter()`, но для mtpp'шного manager'а. Вот [дока](https://django-mptt.readthedocs.io/en/latest/models.html?highlight=get_ancestors#the-treemanager-custom-manager).

2023-02-26 09:59 UTC, ADYason commented on src/apps/bot/handlers.py
> +    from .models import CoverageArea
Мне это видится невозможным. Я писал об этом в [треде](https://app.pachca.com/chats?thread_id=305101) в самом начале. Первое сообщение. Второй пункт.

2023-02-26 09:59 UTC, ADYason commented on src/apps/bot/handlers.py
>      print("start user_data:", context.user_data)  # FIXME: удалить
Убрано

2023-02-26 09:59 UTC, ADYason commented on src/apps/bot/handlers.py
> +    async for region in CoverageArea.objects._mptt_filter(level=1):
Без `async` неполучится, тк при последовательном обращении к бд бот ломается. Я писал об этом в [треде](https://app.pachca.com/chats?thread_id=305101) в самом начале. Первое сообщение.

2023-02-26 10:19 UTC, ADYason commented on src/apps/bot/handlers.py
> +        regions_buttons.insert(0, [InlineKeyboardButton(region.name, callback_data=region.name)])
Исправлено

2023-02-26 10:20 UTC, ADYason commented on src/apps/bot/handlers.py
> +    async for region in CoverageArea.objects._mptt_filter(level=0):
Скрин каст есть в [треде](https://app.pachca.com/chats?thread_id=305101)

2023-02-26 15:52 UTC, kr0t approved these changes

2023-02-26 15:53 UTC, merged