funds from db
Studio-Yandex-Practicum/mspp pull request #30
Opened 2023-03-11 11:28 UTC by ADYason

2023-03-13 21:35 UTC, kr0t requested changes

2023-03-13 21:35 UTC, kr0t commented on src/apps/bot/handlers.py
> +        # TODO пагинация?
Это надо убрать.

2023-03-13 21:35 UTC, kr0t commented on src/apps/bot/handlers.py
> +    async for fund in Fund.objects.filter(coverage_area__name=context.user_data[CITY]):
Ты тут отбираешь фонды только по одному критерию - город. Но есть ограничение на возраст, которое необходимо учитывать. На user-flow это описано.

2023-03-14 15:34 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +    from .models import Fund
Зачем тут импорты? Вложеного импорта не вижу, тогда почему бы их не убрать в шапку?

2023-03-14 18:25 UTC, ADYason commented on src/apps/bot/handlers.py
> +    from .models import Fund
Большой тред,в нем первое сообщение, почему в шапку нельзя вынести импорт моделей для хендлера.
https://app.pachca.com/chats/4208046?thread_id=305101

2023-03-14 18:54 UTC, ADYason commented on src/apps/bot/handlers.py
> +        # TODO пагинация?
Поправил

2023-03-14 18:54 UTC, ADYason commented on src/apps/bot/handlers.py
> +    async for fund in Fund.objects.filter(coverage_area__name=context.user_data[CITY]):
Поправил

2023-03-14 19:34 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +    from .models import Fund
Перенеси импорт функции `start_bot` в метод `ready` у `BotConfig` (в файле src/apps/bot/apps.py). Должно заработать без этого костыля.

2023-03-15 21:55 UTC, kr0t approved these changes

2023-03-15 21:56 UTC, merged