local_launch
Studio-Yandex-Practicum/mspp pull request #31
Opened 2023-03-11 12:51 UTC by AlexGriv

изменён локальный запуск,
 только контейнер базы- docker compose -f infra/docker-compose_db_launch.yml up 
-d --build
 запуск приложения через IDE - python manage.py runserver или uvicorn config.asgi:application

2023-03-13 17:12 UTC, NiKuma0 commented
Честно не вижу резона запускать через uvicorn. Если локальный запуск нужен для программиста, то ему удобнее пользоваться Django, `python manage.py startserver`

2023-03-13 21:31 UTC, kr0t requested changes
Не мог понять, что меня смущает в названии наших файлов compose, например `docker-compose_db_launch.yml` - так это смешение `-` и `_`.
Полистал документацию по Docker и нашел хорошие примеры, которые как мне кажется - https://docs.docker.com/compose/reference/#specifying-multiple-compose-files . Аналогичный подход я уже использовал 
![image](https://user-images.githubusercontent.com/7937377/224836419-ff4f4a8e-d07f-46b6-851d-35048867ff8d.png)
Предлагаю исправить по такому же принципу.
@NiKuma0, @AntonZelinsky что думаете?

2023-03-13 21:31 UTC, kr0t commented on infra/docker-compose_db_launch.yml
> +version: '3.8'
Теперь версию не надо указывать - [см.тут](https://docs.docker.com/compose/compose-file/#compose-file)

2023-03-13 21:31 UTC, kr0t commented on README.md
> +  <summary>Запуск только контейнера базы данных для более удобной разработки</summary>
```suggestion
  <summary>Локальный запуск приложения с использованием БД в Docker</summary>
```

Может как-нибудь поправим? У тебя в инструкции не только про запуск БД в докере, но и самого приложения.

2023-03-13 21:31 UTC, kr0t commented on .github/workflows/stage_deploy.yml
> +name: Stage_Deploy
А зачем тут `_`? Это же название деплоя, а не переменная. Предлагаю вернуть.

2023-03-13 21:31 UTC, kr0t commented on README.md
> +[![MSPP Actions Status](https://github.com/Studio-Yandex-Practicum/mspp/actions/workflows/stage_deploy.yaml/badge.svg)](https://github.com/Studio-Yandex-Practicum/mspp/actions)
Как и выше ты тут перерефакторил...Предыдущий бейдж отражал среду деплоя, по нему сразу понятно что на stage деплой отработал/не отработал. К тому же будет второй бейдж для мастер ветки.

2023-03-13 21:31 UTC, kr0t commented on README.md
> +  <summary>Запуск только контейнера базы данных для более удобной разработки</summary>
Вообще я предлагаю не прятать документацию под summary. Нарушается читабельность, сложно найти необходимую информацию без лишних манипуляций. У нас README не такой большой, лучше его красиво отформатировать, чем прятать по кусочкам.

2023-03-14 14:54 UTC, NiKuma0 requested changes

2023-03-14 14:54 UTC, NiKuma0 commented on infra/docker-compose_db_launch.yml
> +    expose:
expose и ports по сути делают одно и тоже ([вот по подробнее про expose](https://docs.docker.com/compose/compose-file/compose-file-v3/#expose)). Лучше использовать только ports.
Отрефач и другие файлы)

2023-03-15 11:39 UTC, AlexGriv commented on .github/workflows/stage_deploy.yml
> +name: Stage_Deploy
Это из за смен веток, засосало в add .

2023-03-15 11:39 UTC, AlexGriv commented on README.md
> +[![MSPP Actions Status](https://github.com/Studio-Yandex-Practicum/mspp/actions/workflows/stage_deploy.yaml/badge.svg)](https://github.com/Studio-Yandex-Practicum/mspp/actions)
Та же петрушка. Это из за смен веток, засосало в add .

2023-03-15 13:04 UTC, NiKuma0 commented
Не могу смержить. Ты, я так понял, тянешь старый код, не охота его добавлять в основную ветку. Можешь поправить? [Вот статейка](https://frontend-stuff.com/blog/updating-git-branch/), может поможет.

2023-03-15 13:24 UTC, AlexGriv commented on infra/docker-compose_db_launch.yml
> +    expose:
файл с expose: только 1 был), поправил

2023-03-15 14:52 UTC, kr0t approved these changes

2023-03-15 15:50 UTC, NiKuma0 approved these changes

2023-03-15 21:52 UTC, merged