Added registration form
Studio-Yandex-Practicum/mspp pull request #41
Opened 2023-03-22 15:25 UTC by alexpro2022

Добавлена форма регистрации для сбора персональных данных пользователя  и дальнейшей отправки в гугл таблицу.

2023-03-22 15:36 UTC, NiKuma0 commented on src/config/settings.py
> +        "DIRS": [os.path.join(BASE_DIR, 'templates')],
```suggestion
        "DIRS": [BASE_DIR / 'templates'],
```

2023-03-22 16:16 UTC, NiKuma0 requested changes

2023-03-22 16:16 UTC, NiKuma0 commented on src/templates/registration.html
> +  <style>
Разбей файл по типам html, css и js

2023-03-23 19:49 UTC, NiKuma0 requested changes

2023-03-23 19:49 UTC, NiKuma0 commented on infra/nginx.conf
> +        proxy_pass http://backend:8000;
Добавь `proxy_set_header` как это сделано ниже.

2023-03-23 19:49 UTC, NiKuma0 commented on src/config/settings.py
> +APPLICATION_URL = env("APPLICATION_URL", default='130.193.48.219')
Наше приложение по сути является статикой, и получать ссылку на него нужно также как и на любой другой статик файл (`static('registration.html')`). Эту настройку нужно убрать. [Вот подробнее](https://docs.djangoproject.com/en/4.1/howto/static-files/#serving-static-files-during-development)

2023-03-23 19:49 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +    if settings.DEBUG:
Используй логгер.

2023-03-25 11:46 UTC, AntonZelinsky commented on .env_example
> +APPLICATION_URL= # домен, на котором развернуто приложение
Чем отличается от webhook_url?

2023-03-25 11:46 UTC, AntonZelinsky commented on infra/nginx_local.conf
> +        proxy_pass http://backend:8000;
Кажется, можно объединить с блоком выше

2023-03-25 11:46 UTC, AntonZelinsky commented on src/templates/includes/surname_field.html
> +    <input id="surname" name="surname" type="text" class="validate" minlength="2" maximumlength="100" required>
Что-то не понятно, есть один большой HTML, есть множество маленьких, что-то тут лишнее. К тому же, маленькие HTML  выглядят как обычные моды джаего, они сюда не подходят? Если нет, то можно сделать кастомный контрол и использовать его.

2023-03-25 11:46 UTC, AntonZelinsky commented on src/templates/includes/surname_field.html
> +    <input id="surname" name="surname" type="text" class="validate" minlength="2" maximumlength="100" required>
А может, это я немного запутался, так как не вижу всего объёма выполняемой задачи. Но всё равно, т т есть над чем поработать

2023-03-25 11:46 UTC, AntonZelinsky commented on src/apps/bot/views.py
> +        context[key] = s.USER_DATA.get(key, ERROR)
Почему сетинги хранят юзер дату мне вообще не понятно

2023-03-25 15:53 UTC, NiKuma0 commented
Портится структура кода. Создать новое приложение в папке src/apps, и туда весь этот код переложи.

2023-03-25 16:37 UTC, alexpro2022 commented on src/templates/includes/surname_field.html
> +    <input id="surname" name="surname" type="text" class="validate" minlength="2" maximumlength="100" required>
Антон, привет! Спасибо за ревью.
Хотел объяснить и заодно прояснить как у вас в команде такие моменты делают.
Начну с самого начала:
Так как у нас две формы:
    -регистрация пользователя на наставничество в конкретном фонде
    -регистрация нового фонда
я сделал (как учили) base.html, который расширяю непосредственно формами - структура , которых одинаковая, различаются только, поля, да и то немного и пять полей совершенно идентичны в двух формах. Поэтому  (опять же как учили))) я их вынес тоже в отдельные файлы по принципу dry и включаю в формах где необходимо. В конечном итоге получается, что нет дублирования кода вообще. С другой стороны может быть читабельность ухудшается, поэтому хотел узнать какие у вас в команде предпочтения? Если вынос одинаковых полей ввода в отдельные файлы излишен - я все в формы вставлю чтобы читаемость стала лучше. Дай знать, pls )))

2023-03-28 20:12 UTC, alexpro2022 commented on src/templates/registration.html
> +  <style>
Разбил файл на типы:
 - структура - HTML
 - стили - CSS
 - валидация ввода - JS

2023-03-28 20:14 UTC, alexpro2022 commented on src/config/settings.py
> +        "DIRS": [os.path.join(BASE_DIR, 'templates')],
убрал этот путь вообще так как шаблоны ушли в отдельное приложение и путь на уровне проекта уже не нужен

2023-03-28 20:17 UTC, alexpro2022 commented on infra/nginx.conf
> +        proxy_pass http://backend:8000;
Три локации объединены в один блок
```py
    location ~ ^/(admin|bot|registration) {
        proxy_pass http://backend:8000;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    } 
```

2023-03-28 20:24 UTC, alexpro2022 commented on .env_example
> +APPLICATION_URL= # домен, на котором развернуто приложение
Нужен фиксированный урл по которому WebApp будет брать формы регистрации пользователя и нового фонда 
```py
DOMAIN = env("DOMAIN", default="https://msppbot.duckdns.org")
...
WEBHOOK_URL = env("WEBHOOK_URL", default=environ.Env.NOTSET if WEBHOOK_MODE else "")
```
а вебхук все-таки не совсем урл приложения, тем более он вариативный (условие if)

2023-03-28 20:26 UTC, alexpro2022 commented on infra/nginx_local.conf
> +        proxy_pass http://backend:8000;
Объединил 

```py
    location ~ ^/(admin|bot|registration) {
        proxy_pass http://backend:8000;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    } 
```

2023-03-28 20:29 UTC, alexpro2022 commented on src/apps/bot/views.py
> +        context[key] = s.USER_DATA.get(key, ERROR)
Да это я погорячился, теперь юзер дата храниться в отдельном приложении registration и не выходит за его пределы

2023-03-28 20:36 UTC, alexpro2022 commented on src/config/settings.py
> +APPLICATION_URL = env("APPLICATION_URL", default='130.193.48.219')
У нас не совсем статика, так приходится передавать в форму пред-заполненные данные (возраст, регион/город, фонд) в рендер, а может я и ошибаюсь ???

2023-03-28 20:43 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +    if settings.DEBUG:
Здесь немного не понял, это вроде не мой кусок

2023-03-29 13:57 UTC, NiKuma0 requested changes
Гораздо лучше, но ещё не идеал)

2023-03-29 13:57 UTC, NiKuma0 commented on Dockerfile
> +CMD ["./start.sh"]
Оставь как было. Этот файл всего на две команды, в нем нет смысла, только читабельность портится. Сам файл тоже удали.

2023-03-29 13:57 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +from config import settings
Сетинги бери из библиотеки Джанго, а не напрямую.

2023-03-29 13:57 UTC, NiKuma0 commented on infra/nginx_local.conf
> +        proxy_pass http://backend:8000/admin/;
Тут можно обойтись одним блоком.

2023-03-29 13:57 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +    await webapp(update, context, settings.WEBAPP_URL_NEW_FUND)
Вместо WEBAPP_URL_* попробуй использовать django.urls.reverse. А переменные удали. Постарайся не добавлять переменные в сетинги, только в крайнем случае.

2023-03-29 13:57 UTC, NiKuma0 commented on src/apps/registration/utils.py
> +    views.USER_DATA = context.user_data
Зачем менять глобальную переменную? Лучше не надо. Можно без нее обойтись.

2023-03-29 17:59 UTC, alexpro2022 commented on src/apps/registration/utils.py
> +    views.USER_DATA = context.user_data
Я через нее передаю пред-заполненные поля (возраст, регион, город , фонд) в контекст шаблона

```py
def rendering(
    request: HttpRequest,
    template_name: str,
    user_data_keys: tuple[str],
) -> HttpResponse:
    ERROR = "Такого поля нет в Контексте"
    context = {}
    for key in user_data_keys:
        context[key] = USER_DATA.get(key, ERROR)
    return render(request, template_name, context)

```

2023-03-29 18:04 UTC, alexpro2022 commented on Dockerfile
> +CMD ["./start.sh"]
Мне нужно статику грузить как-то, а вручную и доступа нет и после каждого деплоя статику руками собирать, тоже как-то ... Если настаиваешь - уберу )

2023-03-29 18:13 UTC, NiKuma0 commented on Dockerfile
> +CMD ["./start.sh"]
Убери файл. У нас статика в воркфлоу собирается. Если прям надо, создай тред в пачке, т.к. придется ещё и воркфлоу менять.

2023-03-29 18:15 UTC, NiKuma0 commented on src/apps/registration/utils.py
> +    views.USER_DATA = context.user_data
Это можно передать иначе. Например, через url query

2023-03-29 20:51 UTC, alexpro2022 commented on infra/nginx_local.conf
> +        proxy_pass http://backend:8000/admin/;
Исправил

```py
    location ~ ^/(admin|bot|registration) {
        proxy_pass http://backend:8000;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }  
```

2023-03-29 20:53 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +from config import settings
Исправил

```py
from django.conf import settings
```

2023-03-29 20:55 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +    await webapp(update, context, settings.WEBAPP_URL_NEW_FUND)
Исправил:

```py

async def new_fund_form(update: Update, context: ContextTypes.DEFAULT_TYPE):
    WEBAPP_URL_NEW_FUND = f"{settings.DOMAIN}{reverse('registration_new_fund')}"
    await webapp(update, context, WEBAPP_URL_NEW_FUND)
    return NEW_FUND

...

async def fund_form(update: Update, context: ContextTypes.DEFAULT_TYPE):
    WEBAPP_URL_USER = f"{settings.DOMAIN}{reverse('registration_new_user')}"
    await webapp(update, context, WEBAPP_URL_USER)
    return FUND

```

2023-03-29 21:49 UTC, kr0t commented
Есть конфликт, надо поправить.

2023-03-30 08:01 UTC, alexpro2022 commented on Dockerfile
> +CMD ["./start.sh"]
Вернул все в исходное состояние

2023-03-30 09:10 UTC, alexpro2022 commented on Dockerfile
> +CMD ["./start.sh"]
Увидел в воркфлоу )))
```py
sudo docker compose -f infra/docker-compose.staging.yml exec backend python manage.py collectstatic --no-input
```

2023-03-30 10:33 UTC, alexpro2022 commented on src/apps/registration/utils.py
> +    views.USER_DATA = context.user_data
Заменил глобальную переменную классом и сделал проверку на DEBUG, чтобы тестовая информация не выводилась в продакшене

2023-04-02 17:44 UTC, NiKuma0 requested changes

2023-04-02 17:44 UTC, NiKuma0 commented on infra/swag_nginx.conf
> +<<<<<<< HEAD:infra/nginx.conf
Исправь конфликт

2023-04-02 17:44 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +logger = logging.getLogger(__name__)
Зачем второй логгер?

2023-04-02 17:44 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +    WEBAPP_URL_NEW_FUND = (
Почему большими буквами?

2023-04-02 17:44 UTC, NiKuma0 commented on src/apps/registration/urls.py
> +    path("new-user/<str:age>/<str:region>/<str:city>/<str:fund>/",
Это не то что я имел ввиду. Можешь пока убрать ?

2023-04-02 17:44 UTC, NiKuma0 commented on src/config/settings.py
> +DOMAIN = env("DOMAIN", default=DEFAULT_DOMAIN)
Тут оставь как было, используй `WEBHOOK_URL`.

2023-04-04 12:39 UTC, alexpro2022 commented on infra/swag_nginx.conf
> +<<<<<<< HEAD:infra/nginx.conf
Исправил

2023-04-04 12:41 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +logger = logging.getLogger(__name__)
Сам не понимаю как  он там прявился )))

2023-04-04 12:41 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +    WEBAPP_URL_NEW_FUND = (
Исправил

2023-04-04 12:43 UTC, alexpro2022 commented on src/apps/registration/urls.py
> +    path("new-user/<str:age>/<str:region>/<str:city>/<str:fund>/",
Никита, я пока оставлю лучше, потому что все прекрасно работает (проверял локально на ngrok) - давай для начала покажем хоть такой результат и тестировщики смогут приступить к своей работе, а я потом отрефакторю как ты скажешь

2023-04-04 12:45 UTC, alexpro2022 commented on src/config/settings.py
> +DOMAIN = env("DOMAIN", default=DEFAULT_DOMAIN)
Подскажи webhook_url - это https://msppbot.duckdns.org ?

2023-04-04 12:53 UTC, NiKuma0 commented on src/config/settings.py
> +DOMAIN = env("DOMAIN", default=DEFAULT_DOMAIN)
(Не помечай чат разрешённым когда ждешь ответа)
webhook_url - это переменная, которая выше в этом же файле.

2023-04-04 13:03 UTC, NiKuma0 approved these changes

2023-04-04 13:03 UTC, NiKuma0 commented on infra/docker-compose.staging.yml
> +      # - STAGING=true
Откуда это тут?

2023-04-04 13:03 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +    webapp_url_new_fund = (
Можно переместить прямо в функцию, без объявления переменных, так код будет чище)

2023-04-04 13:03 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +        await location(update, context)  # suppose to be a method fund, but it doesn't work
Добавь `return` - снизь вложенность кода

2023-04-04 13:03 UTC, NiKuma0 commented on src/config/settings.py
> +DOMAIN = env("WEBHOOK_URL", default="https://msppbot.duckdns.org")
Убери эту переменную, вместо нее используй `WBHOOK_URL` (переменную)

2023-04-04 13:09 UTC, alexpro2022 commented on src/config/settings.py
> +DOMAIN = env("DOMAIN", default=DEFAULT_DOMAIN)
Это переменная окружения, а у меня нет доступа к серверу чтобы проверить .env файл поэтому и спрашиваю, какой протокол и домен будет фигурировать )

2023-04-04 13:11 UTC, alexpro2022 commented on infra/docker-compose.staging.yml
> +      # - STAGING=true
Это я с твоего деплоя скопировал, чтобы с твоей последней версией не конфликтовать

2023-04-04 13:20 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +    webapp_url_new_fund = (
Исправил

2023-04-04 13:21 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +        await location(update, context)  # suppose to be a method fund, but it doesn't work
Исправил

2023-04-05 18:49 UTC, NiKuma0 requested changes

2023-04-05 18:49 UTC, NiKuma0 commented on src/apps/bot/handlers.py
> +        f"https://msppbot.duckdns.org"
Тут используй `WEBHOOK_URL` (и ниже тоже) 
```suggestion
        f"https://{setings.WEBHOOK_URL}"
```

2023-04-06 17:34 UTC, NiKuma0 commented on infra/docker-compose.staging.yml
> +      - CERTPROVIDER=zerossl
Перемести это в отдельную ветку. Там подумаем

2023-04-06 19:38 UTC, alexpro2022 commented on infra/docker-compose.staging.yml
> +      - CERTPROVIDER=zerossl
Никита, я не могу больше терять время на бюрократию с разными ветками (так как 9 апреля заканчиваю курс обучения и хотел бы допилить формы, но они зависят от ssl-сертификата) - это решениe (сменить провайдера на 
zerossl при бане от lets encrypt, который использутся свагом по умолчанию) указанно в официальной SWAG документации, я ничего нового не придумал, просто тщательно прочитал оригинал документации ) Поэтому и обсуждать здесь особенно нечего, надеюсь ты согласишься со здравым смыслом)

2023-04-06 19:49 UTC, alexpro2022 commented on src/apps/bot/handlers.py
> +        f"https://msppbot.duckdns.org"
Насчет загадочного вебхука , который в  моем webapp будет смотреться как седло на корове, лучше сделать понятную всем переменную окружения типа DOMAIN или (если с протоколом сразу надо) то APPLICATION_URL и использовать ее и в webapp и в webhook ( это даже более логично), про самодокументирование кода что-то слышали? Это когда сущностям дают максимально понятные названия, чтобы сразу было понятно, что эта сущность делает )))  Что делает вебхук из названия не понятно, даже после курса обучения 14 месяцев по программе Python-разработчик plus, меня этому не учили, к сожалению.

2023-04-07 20:59 UTC, kr0t commented on infra/docker-compose.staging.yml
> +      - CERTPROVIDER=zerossl
@alexpro2022 Ок, пусть будет zerossl. А что за `email` ты указал для этого? Что туда приходит и у кого туда есть доступ?

2023-04-08 12:58 UTC, NiKuma0 commented on infra/docker-compose.staging.yml
> -      - keys:/config/keys
Оставь мои ключи. Они не как не мешают)

2023-04-08 15:08 UTC, NiKuma0 approved these changes

2023-04-08 15:08 UTC, merged