Загрузка данных из формы нового фонда в гугл-таблицу
Studio-Yandex-Practicum/mspp pull request #55
Opened 2023-04-21 19:16 UTC by Wotan-son

2023-04-23 09:11 UTC, NiKuma0 requested changes
Убери статику

2023-04-23 09:11 UTC, NiKuma0 commented on src/apps/bot/handlers.py
>      # TODO: передать данные из формы в google таблицу
Убери

2023-04-23 12:01 UTC, Wotan-son commented on src/apps/bot/handlers.py
>      # TODO: передать данные из формы в google таблицу
Поправил

2023-04-23 21:46 UTC, kr0t reviewed
А что ты сделал, чтобы внести правки почти в весь проект? Как найти твои доработки по задаче?
И у тебя конфликт, надо поправить.

2023-04-24 08:38 UTC, Wotan-son commented
> А что ты сделал, чтобы внести правки почти в весь проект? Как найти твои доработки по задаче? И у тебя конфликт, надо поправить.

1. Как внеслись, как будто бы внеслись правки в весь проект вообще не представляю. 2. Правки вносил в handlers.py в функцию async def read_new_fund_form 3. С конфликтом сейчас буду разбираться.

2023-04-27 12:45 UTC, NiKuma0 commented
Я не знаю как такое проверять - все файлы добавлены в индекс. Попробуй пересоздать ветку, начни с нуля...

2023-04-27 12:45 UTC, closed without merging