add: workflows\stage_deploy.yaml
Studio-Yandex-Practicum/mspp pull request #6
Opened 2023-01-28 19:56 UTC by Esedess

Набросал болванку для тестового деплоя по образу и подобию Любимовки.

2023-01-28 22:28 UTC, kr0t requested changes

2023-01-28 22:28 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +      - an_unknown_branch_that_will_never_be_created
Что это? Тут должна быть develop ветка.

2023-01-28 22:28 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +  tests:
Я не уверен в необходимости этого блока с тестами. Предлагаю пока его не добавлять, если появятся тесты мы его вернем.

2023-01-28 22:28 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +  push:
Давай изменим триггер на закрытый PR

2023-01-28 22:28 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +      - name: Create SSH key
Можешь рассказать, в чем необходимость это шага?

2023-01-28 22:28 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +      - name: Make envfile
А где будет создан `env` файл?

2023-01-28 22:28 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +# При желании можно отправить соощение в телеграм
Лишние комменты надо убрать.

2023-01-29 15:33 UTC, Esedess commented on .github/workflows/stage_deploy.yaml
> +      - name: Create SSH key
Добавляет id_rsa и known_hosts в юзера на машине на которой запущен workflow.
Фактически позволяет удостовериться, что хост "тот самый", на нем не поменялись настройки и оборудование.
Далее при установке SSH-соединения клиент самостоятельно пройдет все стандартные шаги верификации
 хоста.
Так же это дает возможность использовать 1 ключ для всех операций и не давать его "левые руки", или, например, использовать тут ключ с доступом на запись и исполнение, а раздавать ключ только на чтение. Вариантов много могу придумать.
Но в плане "необходимости" не могу сказать - что будет за сервер? у кого будет доступ? кто будет его настраивать? и тд. Но сам шаг полезный.

2023-01-30 21:59 UTC, kr0t reviewed
Давай ещё добавим ручной запуск деплоя + комменты по коду.

2023-01-30 21:59 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +      - name: Create SSH key
Я просто хотел понять, в чем отличие этого подхода от того, что используется ниже - `appleboy/ssh-action`
По сути 6 строчек подготовки нужны для того, чтобы выполнять команды с раннера гитхаба на сервер где должно быть развернуто приложение.
Давай будем использовать единообразный подход.

2023-01-30 21:59 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +        run: scp -r infra/stage/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ env.DEPLOY_PATH }}
А откуда берется каталог `infra/stage/`? Что ты копируешь?

2023-01-31 08:40 UTC, kr0t commented on .github/workflows/stage_deploy.yaml
> +  DEPLOY_PATH: '???'
Предлагаю выбрать такой путь /MSPP

2023-01-31 13:56 UTC, Esedess commented
Оставил минимум. Остальное дополнять на реальном деплое

2023-01-31 20:12 UTC, kr0t approved these changes

2023-02-02 20:57 UTC, merged